language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y qt5-default qt5-qmake libqt5svg5

script:
  - qmake -qt=qt5
  - make
