language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y qt5-qmake qtbase5-dev libqt5core5 libqt5gui5 libqt5opengl5 libqt5svg5 libqt5xml5

script:
  - qmake -qt=qt5
  - make
