language: cpp

compiler:
  - gcc
  - clang

before_install:
  - wget https://dl.dropboxusercontent.com/u/41666920/orientview-travis/ffmpeg.tar.xz -P /var/tmp
  - wget https://dl.dropboxusercontent.com/u/41666920/orientview-travis/l-smash.tar.xz -P /var/tmp
  - wget https://dl.dropboxusercontent.com/u/41666920/orientview-travis/opencv.tar.xz -P /var/tmp
  - wget https://dl.dropboxusercontent.com/u/41666920/orientview-travis/qt.tar.xz -P /var/tmp
  - wget https://dl.dropboxusercontent.com/u/41666920/orientview-travis/x264.tar.xz -P /var/tmp
  - tar xf /var/tmp/ffmpeg.tar.xz -C /var/tmp
  - tar xf /var/tmp/l-smash.tar.xz -C /var/tmp
  - tar xf /var/tmp/opencv.tar.xz -C /var/tmp
  - tar xf /var/tmp/qt.tar.xz -C /var/tmp
  - tar xf /var/tmp/x264.tar.xz -C /var/tmp

# sudo apt-get update -qq
# sudo apt-get install -y mesa-common-dev
# sudo apt-get install -y libgl1-mesa-dev

script:
  - /var/tmp/qt/5.3/gcc_64/bin/qmake
  - make

